# file: roles/ssh_proxy/tasks/main.yaml
---

- name: Read the ansible_user_id getent passwd database
  getent:
    database: passwd
    key: "{{ ansible_user_id }}"

- name: Resolve home directory location
  set_fact:
    home_dir: "{{ getent_passwd[ansible_user_id][4] }}"

- name: SSH user configuration directory
  file:
    state: directory
    dest: "{{ home_dir }}/.ssh/config.d"
    mode: 0700

- name: SSH proxy host configuration
  template:
    src: "ssh_config_guests.j2"
    dest: "{{ home_dir }}/.ssh/config.d/{{ hostname }}_guests"
    mode: 0600
