---
# file: roles/dynect_dns_record/tasks/main.yml

#
# DynECT ZoneAddNode user permission is required to add records. 
#
- name: Make DNS A records
  when: dynect_session_result|success
  local_action: >
                command curl -s -X POST -H 'Content-Type: application/json'
                -H 'Auth-Token: {{ dynect_session_token }}'
                {{ dynect_api_url }}/ARecord/{{ dns_zone }}/{{ hostname }}.
                -d '{"rdata":{"address":"{{ inventory_hostname }}"}}'

#
# roles/hetzner_rescue_centos sets the sshfp_records
#

- name: Delete old DNS SSHFP records
  when: sshfp_records is defined and sshfp_records|success
  local_action: >
                command curl -s -X DELETE -H 'Content-Type: application/json'
                -H 'Auth-Token: {{ dynect_session_token }}'
                {{ dynect_api_url }}/SSHFPRecord/{{ dns_zone }}/{{ hostname }}/

- name: Make DNS SSHFP records
  when: sshfp_records is defined and sshfp_records|success
  local_action: >
                command curl -s -X POST -H 'Content-Type: application/json'
                -H 'Auth-Token: {{ dynect_session_token }}'
                {{ dynect_api_url }}/SSHFPRecord/{{ dns_zone }}/{{ hostname }}/
                -d '{"rdata":{
                "algorithm":"{{ item | regex_replace('^[^ ]+ IN SSHFP ([123]) [12] .*$', '\\1') }}",
                "fptype":"{{ item | regex_replace('^[^ ]+ IN SSHFP [123] ([12]) .*$', '\\1') }}",
                "fingerprint":"{{ item | regex_replace('^[^ ]+ IN SSHFP [123] [12] (.*)$', '\\1') }}"
                }}'
  with_items: sshfp_records.stdout_lines

- name: Publish DNS zones
  when: dynect_session_result|success
  local_action: >
                command curl -s -X PUT -H 'Content-Type: application/json'
                -H 'Auth-Token: {{ dynect_session_token }}'
                {{ dynect_api_url }}/Zone/{{ dns_zone }} -d '{"publish":true}'
