# file: roles/ansible_inventory/tasks/main.yml
#
# Adds freshly provisioned managed servers to the target inventory.
#
---

- name: Compare the target repository status with upstream
  run_once: yes
  local_action: >
                command chdir="{{ inventory_dir }}"
                git rev-list HEAD@{upstream}..HEAD
  register: repo_status
  changed_when: False

- name: Check that there are no pending commits
  run_once: yes
  fail: >
        msg="The target repository is ahead of upstream
        by the following commit(s): {{ repo_status.stdout_lines | join(' ') }}"
  when: repo_status.stdout.strip() != ""

- name: Ensure hypervisor target inventory group exists
  local_action: >
                lineinfile
                dest="{{ inventory_dir }}/{{ target_ansible_inventory }}"
                regexp="^\[{{ target_ansible_group }}\]"
                line="[{{ target_ansible_group }}]"
                state=present

- name: Ensure hypervisor appears under the target inventory group
  local_action: >
                lineinfile dest="{{ inventory_dir }}/{{ target_ansible_inventory }}"
                regexp="^{{ hostname }}" line="{{ hostname }}"
                insertafter="^\[{{ target_ansible_group }}\]"
                state=present

- name: Ensure target inventory host_vars directory exists
  run_once: yes
  local_action: file state=directory path="{{ inventory_dir }}/host_vars"

- name: Add new hypervisor host_vars (retain existing)
  local_action: >
                template force=no backup=yes src=libvirt_host_centos_host_vars.j2
                dest="{{ inventory_dir }}/host_vars/{{ hostname }}"

- name: Ensure guest target inventory group exists
  local_action: >
                lineinfile force=no
                dest="{{ inventory_dir }}/{{ hostvars[item].target_ansible_inventory }}"
                regexp="^\[{{ hostvars[item].target_ansible_group }}\]"
                line="[{{ hostvars[item].target_ansible_group }}]"
                state=present
  with_items: groups['{{ libvirt_guests_group }}']

- name: Ensure guest appears under the target inventory group
  local_action: >
                lineinfile dest="{{ inventory_dir }}/{{ hostvars[item].target_ansible_inventory }}"
                regexp="^{{ item }}" line="{{ item }}"
                insertafter="^\[{{ hostvars[item].target_ansible_group }}\]"
                state=present
  with_items: groups['{{ libvirt_guests_group }}']

- name: Add new guest host_vars (retain existing)
  local_action: >
                template force=no backup=yes src=libvirt_guest_centos_host_vars.j2
                dest="{{ inventory_dir }}/host_vars/{{ item }}"
  with_items: groups[libvirt_guests_group]
