# file: roles/ansible_inventory/tasks/main.yml

#
# Adds freshly provisioned managed servers to the target inventory.
#

- name: Checkout the target Ansible repository
  run_once: yes
  local_action: >
                command chdir="{{ target_ansible_parent | mandatory }}"
                git clone {{ target_ansible_repo_url | mandatory }} {{ target_ansible_repo_name | mandatory }}
                creates="{{ target_ansible_repo_name }}"

- name: Check that there are no pending commits
  run_once: yes
  local_action: >
                command chdir="{{ target_ansible_parent }}/{{ target_ansible_repo_name }}"
                git status
  register: status_result
  changed_when: False 
  failed_when: "'Your branch is ahead of' in status_result.stdout"

- name: Add hosts under the target inventory group
  local_action: >
                lineinfile dest="{{ target_ansible_parent | mandatory }}/{{ target_ansible_repo_name }}/{{ target_ansible_inventory }}"
                regexp="^{{ hostvars[inventory_hostname].hostname }}" line="{{ hostvars[inventory_hostname].hostname }}"
                insertafter="^\[{{ target_ansible_group | mandatory }}\]"
                state=present

- name: Add host_vars
  local_action: >
                template backup=yes src=host_vars.j2
                dest="{{ target_ansible_parent | mandatory }}/{{ target_ansible_repo_name }}/host_vars/{{ hostvars[inventory_hostname].hostname }}"
