# file: guests.yaml
#
# Installs virtual guest machines on the hypervisors. Usually run as:
#
# ansible-playbook -vv guests.yaml -i ../com.example_main_ansible/development
#
---

- name: START
  hosts: localhost
  connection: local
  tasks:
  - debug:
      msg: "{{ ansible_date_time.iso8601 }}"

- name: GUESTS
  hosts: libvirt_hosts
  vars_files:
  - "{{ playbook_dir | dirname }}/service_commons_ansible/roles/dynect_session/vars/main.yaml"
  roles:
  - libvirt_guests_centos
  - libvirt_guests_dhcp

#
# ~ 30 s from start
#

- name: FINISH
  hosts: localhost
  connection: local
  tasks:
  - debug:
      msg: "{{ ansible_date_time.iso8601 }}"
  - debug:
      msg: "Guest installation will complete in about 8 minutes."

#
# The unattended installation will complete at ~ 8 minutes from start.
#
