# file: hypervisors.yml
#
# Prepares hypervisors for hosting virtual guest machines.
#

- hosts: libvirt_hosts
  vars_files:
    - /mnt/sensitive_data/etc/ansible/vars/admin_access.yml
  roles:
    - dynect_dns_record
    - hetzner_reverse_dns
    - network_hostname
    - hetzner_bridged_networking
    - linux_kvm
    - libvirt_pools
