# file: managed_servers.yml
#
# Prepares new hosts for Ansible configuration management. Usually run as:
#
# ansible-playbook -vv managed_servers.yml -ki bootstrap
#
- hosts: libvirt_hosts
  roles:
    - admin_access
    - admin_tools
    - firewall

