# file: terminate.yaml
#
# Decommission hosts that are no longer required.
#
# ansible-playbook -vvv terminate.yaml -i decommission
#
---

- hosts: libvirt_hosts
  roles:
  - libvirt_guests_terminate

- hosts: ex_libvirt_hosts
  gather_facts: no
  roles:
  - hetzner_robot_server_cancellation
