# file: roles/hetzner_reverse_dns/tasks/main.yml
---

- name: Update Hetzner server names
  local_action:
    module: uri
    method: POST
    url: "{{ hetzner_api_url }}/server/{{ inventory_hostname }}"
    user: "{{ hetzner_api_user }}"
    password: "{{ hetzner_api_password }}"
    body: "server_name={{ hostvars[inventory_hostname].hostname }}"

- name: Update Hetzner reverse DNS records
  local_action:
    module: uri
    method: POST
    url: "{{ hetzner_api_url }}/rdns/{{ inventory_hostname }}"
    user: "{{ hetzner_api_user }}"
    password: "{{ hetzner_api_password }}"
    body: "ptr={{ hostvars[inventory_hostname].hostname }}"
