---
# file: roles/admin_forget/tasks/main.yaml

# Removes previously known host keys before reinstalling the same servers.

- name: Locally remove SSH known host keys
  local_action: "command ssh-keygen -R {{ item }}"
  with_items:
  - "{{ inventory_hostname }}"
  - "{{ hostvars[inventory_hostname].hostname }}"
  - "[{{ inventory_hostname }}]:{{ admin_ssh_port }}"
  - "[{{ hostvars[inventory_hostname].hostname }}]:{{ admin_ssh_port }}"
