---
# file: roles/gpg_keys/tasks/main.yml

#
# Deploys administrative GPG public keys
#
# You must have the keys in your local GnuPG keyring before applying this role.
#

- name: Validate the given administrative GPG public key ids and timestamps
  with_items: gnupg_trusted_keys
  when: not (
        item.id     |match("^[0-9@A-Za-z-.,_]+$") and
        item.fp     |match("^[0-9A-F]{40}$") and
        item.created|match("^[0-9]{4}-[0-9]{2}-[0-9]{2}$")
        )
  local_action: command echo Invalid GPG key entry
                id=\"{{ item.id }}\"
                fp=\"{{ item.fp }}\"
                created=\"{{ item.created }}\"
  failed_when: True

- name: Export trusted GPG public keys from local GnuPG keyring
  with_items: gnupg_trusted_keys
  local_action: command gpg --armor --export "{{ item.id | mandatory }}"
  register: gnupg_exported_keys
  changed_when: False
  failed_when: gnupg_exported_keys.stderr.strip() != "" or
               gnupg_exported_keys.stdout.strip() == ""

- name: Ensure ~/.gnupg/ exists
  file: state=directory path=~/.gnupg mode=700

- name: Write the GPG public keys to files
  with_items: gnupg_exported_keys.results
  copy: dest="~/.gnupg/{{ item.item.id }}_{{ item.item.created | mandatory }}_pub.asc"
        content="{{ item.stdout }}"

- name: Import GPG public keys
  with_items: gnupg_exported_keys.results
  command: chdir="~/.gnupg"
           gpg --import "{{ item.item.id }}_{{ item.item.created | mandatory }}_pub.asc"
  register: gnupg_imported_keys
  changed_when: ("imported" in gnupg_imported_keys.stderr)
  failed_when: (gnupg_imported_keys.rc != 0) or
               (not "processed" in gnupg_imported_keys.stderr)

#
# The value of 6 when importing ownertrust corresponds to 5 ('ultimate') in the
# menu of command: gpg --edit-key trust
#
- name: Fully trust the GPG public keys imported above
  with_items: gnupg_exported_keys.results
  shell: echo "{{ item.item.fp | mandatory }}:6:"
         | gpg --import-ownertrust
  register: gnupg_ownertrust
  changed_when: gnupg_ownertrust.stderr.strip() != ""
