---
# file: roles/hetzner_rescue_activate/tasks/main.yml

#
# Activates the Hetzner rescue system for CentOS installation 
#

#
# Sign on the target system via SSH using the rescue system password
# from the Hetzner Webservice API.
#

- name: Check the rescue system status
  no_log: True
  local_action: command curl -su '{{ hetzner_api_user }}:{{ hetzner_api_password }}'
                {{ hetzner_api_url }}/boot/{{ inventory_hostname }}/rescue
  register: hetzner_rescue
  changed_when: (hetzner_rescue.stdout|from_json).rescue.active

- name: Deactivate the rescue system
  when: hetzner_rescue|changed
  no_log: True
  local_action: command curl -su '{{ hetzner_api_user }}:{{ hetzner_api_password }}'
                -X DELETE {{ hetzner_api_url }}/boot/{{ inventory_hostname }}/rescue

- name: Activate the rescue system
  no_log: True
  local_action: command curl -su '{{ hetzner_api_user }}:{{ hetzner_api_password }}'
                {{ hetzner_api_url }}/boot/{{ inventory_hostname }}/rescue
                -d 'os=linux&arch=64'
  register: hetzner_rescue
  changed_when: (hetzner_rescue.stdout|from_json).rescue.active

- name: Use the rescue root password
  when: hetzner_rescue|changed
  no_log: True
  set_fact:
    ansible_ssh_pass: "{{ (hetzner_rescue.stdout|from_json).rescue.password }}"

- name: Hard reset
  when: hetzner_rescue|changed
  no_log: True
  local_action: command curl -su '{{ hetzner_api_user }}:{{ hetzner_api_password }}'
                {{ hetzner_api_url }}/reset/{{ inventory_hostname }}
                -d type=hw
  register: hetzner_reset
  failed_when: not 'server_number' in hetzner_reset.stdout
