# file: roles/hetzner_session/tasks/main.yml

# Starts a Hetzner Webservice API session.
#
# Create the webservice user in Hetzner robot under Settings
# and configure /mnt/sensitive_data/etc/ansible/vars/hetzner.yml with:
#hetzner_api_user: "your username"
#hetzner_api_password: "your password"
#

- name: Loading Hetzner Webservice access credentials
  sudo: yes
  run_once: yes
  no_log: True
  include_vars: /mnt/sensitive_data/etc/ansible/vars/hetzner.yml

- name: Ensure Ansible local facts directory exists
  sudo: yes
  run_once: yes
  local_action: file state=directory path=/etc/ansible/facts.d owner=root group=root mode=0755
