# file: roles/ssh_bastion/tasks/main.yaml
---

- name: SSH bastion host configuration
  local_action:
    module: template
    src: "ssh_config_guests.j2"
    dest: "{{ ansible_user_dir }}/.ssh/config.d/{{ hostname }}_guests"
    mode: 0600
