---
# file: roles/ssh_known_hosts/tasks/main.yml

#
# SSH known hosts management
#

- name: Ensure that the SSH known hosts file exists
  file: dest="/home/{{ admin_username }}/.ssh/known_hosts" state=touch mode=600

- name: Remove previously known hosts
  when: ssh_known_hosts is defined
  with_subelements:
  - ssh_known_hosts | default([])
  - hosts
  command: ssh-keygen -R {{ item.1 }}

- name: Remove the redundant known hosts backup file
  file: dest="/home/{{ admin_username }}/.ssh/known_hosts.old" state=absent

- name: Add known hosts
  when: ssh_known_hosts is defined
  with_items: ssh_known_hosts|default([])
  lineinfile: dest="/home/{{ admin_username }}/.ssh/known_hosts"
              line="{{ item.hosts|join(',') | mandatory
              }} {{ item.key | mandatory }}"
