# file: roles/hetzner_bridged_networking/tasks/main.yml
#
# Hetzner CentOS bridged networking for additional IP addresses (virtualization)  
# See: http://wiki.hetzner.de/index.php/Netzkonfiguration_CentOS/en#Bridged
#
---

- name: Ensure bridge-utils is present
  become: yes
  yum: name=bridge-utils state=present

- name: Configure network bridge br0
  when: ansible_os_family == "RedHat"
  become: yes
  template: src=ifcfg-br0.j2
            dest=/etc/sysconfig/network-scripts/ifcfg-br0
            owner=root group=root mode=0644

- name: Configure network interface eth0
  when: ansible_os_family == "RedHat" and ansible_eth0.ipv4 is defined
  become: yes
  template: src=ifcfg-eth0.j2 
                dest=/etc/sysconfig/network-scripts/ifcfg-eth0
                owner=root group=root mode=0644

- name: Move the default route to the bridge br0
  become: yes
  command: chdir="/etc/sysconfig/network-scripts/" creates="route-br0" mv route-eth0 route-br0

- name: Fix the default route comments on bridge br0
  become: yes
  lineinfile: dest=/etc/sysconfig/network-scripts/route-br0 regexp="^#\s*routing\s+for" line="# routing for br0"

- name: Ensure bridged networking is configured
  become: yes
  command: ip link show br0
  register: br0_configured
  changed_when: br0_configured.rc != 0
  failed_when: False
  notify:
  - Restart network

- name: Enable IPv4 forwarding
  become: yes
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes

- name: Change the virbr0 interface to the internal firewall zone
  become: yes
  command: firewall-cmd --permanent --zone=internal --change-interface=virbr0

- name: Ensure IPv4 forwarding is enabled
  command: cat /proc/sys/net/ipv4/ip_forward
  register: ipv4_forward
  changed_when: "'0' in ipv4_forward.stdout"
  notify:
  - Restart network
