# file: roles/libvirt_guests_centos/tasks/main.yml
#
# Generates libvirt virt-install scripts for CentOS guests on hypervisors
# and runs them to install guests (unless they already exist).
#
# One virt-install script and kickstart file are generated for each guest
# on each hypervisor.
#

#
# Set the variable libvirt_guests_group for a hypervisor to provision the
# virtual guests in that group on that hypervisor.
#

#
# On CentOS or Fedora, to create a PBKDF2 protected password, you can use:
# grub2-mkpasswd-pbkdf2
#
# Change the guest root password at first login immediately after provision
# of the new virtual machine in a private network.
# On CentOS, to create an SHA-512 hashed password, you can use:
# grub-crypt --sha-512
#
# Set the following variables in file:
# /mnt/sensitive_data/etc/ansible/vars/admin_access.yml
#
#guest_bootpw_pbkdf2:
#guest_rootpw_sha512:

#
# It's worth checking that the guest will be able to download the EPEL RPM
# during its kickstart installation.
#
- name: Check that the EPEL RPM is available from the hypervisor
  with_items: groups['{{ libvirt_guests_group | mandatory }}']
  sudo: yes
  get_url: url="{{ epel_rpm_url|mandatory }}"
           dest=/opt/ force=yes
           sha256sum="{{ epel_rpm_sha256|mandatory }}"

- name: Ensure user home ~/bin directory exists
  file: state=directory path=~/bin mode=0750

- name: Ensure user home ~/kickstart directory exists
  file: state=directory path=~/kickstart mode=0750

- name: Check which guests already exist
  sudo: yes
  shell: virsh -q dominfo "{{ item }}"
  with_items: groups['{{ libvirt_guests_group | mandatory }}']
  register: domains
  changed_when: domains.rc != 0 and 'Domain not found' in domains.stderr
  failed_when: False

- name: Generate libvirt guest installation scripts in ~/bin/
  template: >
            src=guest-install.sh.j2
            dest="~/bin/guest_{{ item }}-install.sh"
            mode=0740
  with_items: groups['{{ libvirt_guests_group | mandatory }}']

- name: Generate libvirt guest configuration files in ~/kickstart/
  no_log: True
  template: >
            src=guest-ks.cfg.j2
            dest="~/kickstart/guest_{{ item }}-ks.cfg"
            mode=0640
  with_items: groups['{{ libvirt_guests_group | mandatory }}']

- name: Install missing guests
  shell: "~/bin/guest_{{ item.item }}-install.sh"
  when: item|changed
  with_items: domains.results
