# file: roles/linux_kvm/tasks/main.yml
---

- name: Virtualization packages
  when: ansible_pkg_mgr == "yum"
  become: yes
  with_items:
  - "@Virtualization"
  - "@Virtualization Client"
  - "@Virtualization Platform"
  - "@Virtualization Tools"
  - kvm
  - libvirt
  - libvirt-python
  - virt-manager
  - virt-viewer
  - libguestfs-tools
  - avahi-dnsconfd
  - xorg-x11-xauth
  yum: name="{{ item }}" state=present

- name: Verify Linux KVM kernel modules
  become: yes
  shell: lsmod | grep kvm
  register: kernel_modules
  changed_when: False
  failed_when: kernel_modules.stdout.find('kvm') == -1

- name: Allow libvirt management access
  with_items:
  - opt: "Identity"
    val: "unix-group:wheel"
  - opt: "Action"
    val: "org.libvirt.unix.manage"
  - opt: "ResultAny"
    val: "yes"
  - opt: "ResultInactive"
    val: "yes"
  - opt: "ResultActive"
    val: "yes"
  become: yes
  ini_file:
    dest: "/etc/polkit-1/localauthority/50-local.d/50-libvirt.pkla"
    section: "libvirt SSH access"
    option: "{{ item.opt }}"
    value: "{{ item.val }}"
    owner: root
    group: root
    mode: 0644
    backup: no

- name: Enable services
  with_items:
  - dbus
  - avahi-daemon
  - libvirtd
  - libvirt-guests
  become: yes
  service: name="{{ item }}" state=started enabled=yes
