---
# file: roles/admin_tools/tasks/main.yml

- name: Tools to support automated administration tasks
  yum: name={{ item }} state=latest
  with_items:
  - python-setuptools
  - gnupg
  - screen
  - nano
  - sysstat
  - procps
  - iptraf
  - tcpdump
  - strace
  - bind-utils
  - net-tools
  - mtr

#  - munin-node
# Fully Automated Nagios (FAN)
# Cacti
