---
# file: roles/dynect_session/tasks/main.yml

# Starts a DynECT DNS management API session.

- name: Load the DynECT API access credentials
  sudo: yes
  run_once: yes
  no_log: True
  local_action: include_vars /mnt/sensitive_data/etc/ansible/vars/dynect.yml

- name: Establish DynECT API session
  no_log: True
  local_action: >
                command curl -s -X POST -H 'Content-Type: application/json'
                {{ dynect_api_url }}/Session/
                -d '{
                "customer_name": "{{ dynect_customer | mandatory }}",
                "user_name": "{{ dynect_api_user | mandatory }}",
                "password": "{{ dynect_api_password | mandatory }}"
                }'
  register: dynect_session_result
  notify: End DynECT API session

- name: Store the DynECT API session as a fact
  when: dynect_session_result|success and
        'success' == (dynect_session_result.stdout|from_json).status
  no_log: True
  set_fact:
    dynect_session_token: "{{ (dynect_session_result.stdout|from_json).data.token | mandatory }}"
