# file: roles/firewall_iptables/tasks/main.yaml
#
# iptables firewall (currently not in use)
#
---

- name: Enable iptables
  become: yes
  service: name=iptables enabled=yes

- name: Open firewall ports (iptables)
  become: yes
  template: src=iptables.j2 dest=/etc/sysconfig/iptables
            owner=root group=root mode=0600
  notify:
  - Restart iptables
