# file: roles/hetzner_robot_server_market/defaults/main.yaml
---

#
# How many (top benefit-cost ratio) servers to order:
#
server_order_count: 2

#
# Server market search criteria for inclusion in the evaluation:
#
server_market:
  memory:
    min: 32
  price:
    max: 35
  hdd_count:
    min: 2
  cpu_benchmark:
    min: 6000
  datacenter:
    pattern: '^HEL.*$'
#  search: "RED.PS" # Red.PS Ent.HDD ECC HWR INIC "SSD" SAS KVM

prefix_multiplier:
  MB: "{{ 1.0 / 1024.0 }}"
  GB: 1.0
  TB: 1024.0

#
# Benefit-cost evaluation criteria
#
# How much more are you willing to pay per unit for
# each server specification attribute; this defines
# the usual expected price of a server:
#
server_market_value:

  cpu:
    benchmark:     0.001

  psu:
    redundant:     5.0

  memory_module:
    '':            0.50
    DDR3:          0.50
    DDR3 ECC:      0.55
    DDR3 ECC reg:  0.60
    DDR4:          0.55
    DDR4 ECC reg:  0.65

  hwr:
    16-Port SATA PCI-E LSI MegaRAID SAS 9260-16i:   20.0
    4-Port SATA PCI-E LSI MegaRAID SAS 9260-4i:     10.0
    4-Port SATA PCI-E Adaptec 5405:                 10.0
    4-Port SATA PCI-E Adaptec 5405 Kit:             10.0
    4-Port SATA PCI-E Adaptec 5405 Single:          10.0
    4-Port SATA PCI-E Adaptec 8405 SGL:             15.0
    4-Port SATA PCI-E 3ware 9650SE-04LPML:           4.0
    2-Port SATA PCI-E 3ware 9650SE-2LP:              2.0
    Intel RAID Expander RES2SV240:                  12.0

  hdd_sata:
    '':           0.003
    Enterprise:   0.004

  hdd_sas:
    '':           0.015

  ssd_sata:
    '':           0.024
    Datacenter:   0.030

  traffic:         0.0005

  nic:
    1 Gbit Intel 82541PI:                     1.0
    1 Gbit Intel 82574L:                      1.0
    1 Gbit Intel 82579LM:                     1.0
    1 Gbit Intel EXPI9301CT:                  3.0
    1 Gbit Intel I210:                        4.0
    1 Gbit Intel I219-LM:                     3.0
    1 Gbit Intel I350:                       10.0
    1 Gbit Intel PWLA8391GT:                  2.0
