# file: roles/hetzner_robot_server_market/defaults/main.yaml
---

#
# How many (top benefit-cost ratio) servers to order:
#
server_order_count: 2

#
# Server market search criteria for inclusion in the evaluation:
#
server_market:
  memory:
    min: 32
  price:
    max: 35
  hdd_count:
    min: 2
  cpu_benchmark:
    min: 6000
  datacenter:
    pattern: '^HEL.*$'
#  search: "RED.PS" # Red.PS Ent.HDD ECC HWR INIC "SSD" SAS KVM


#
# Benefit-cost evaluation criteria
#
# How many units of each server specification attribute
# you may expect to get per euro; this defines the usual
# expected price of a server:
#
server_market_per_euro:
  traffic_TB:       2.0
  cpu_benchmark: 1000.0
  memory_GB:        2.0
  hdd_GB:         340.0

#
# How much more are you willing to pay for each special feature
# (linearly cumulative), relative to the usual expected price (1.0)
# of a server:
#
server_market_factor:
  ent_hdd: 0.05
  ecc:     0.10
  inic:    0.05
  red_ps:  0.10
  hwr:     0.05
  ssd:     0.15
  sas:     0.03
  kvm:     0.03

prefix_multiplier:
  MB: "{{ 1.0 / 1024.0 }}"
  GB: 1.0
  TB: 1024.0

server_market_value:

  cpu:
    benchmark:     0.001

  psu:
    redundant:     5.0

  memory_module:
    '':            0.5
    DDR3:          0.5
    DDR3 ECC:      0.6
    DDR3 ECC reg:  0.6
    DDR4 ECC reg:  0.6

  hwr:
    4-Port SATA PCI-E - LSI MegaRAID SAS 9260-4i: 15.0
    4-Port SATA PCI-E - Adaptec 5405:             15.0
    4-Port SATA PCI-E - Adaptec 5405 Single:      15.0

  hdd_sata:
    '':           0.003
    Enterprise:   0.004

  hdd_sas:
    '':           0.006

  ssd_sata:
    '':           0.005
    Datacenter:   0.006

  traffic:         0.0005

  nic:
    1 Gbit - Intel I210:                            3.0
    1 Gbit - Intel I350:                            3.0
    1 Gbit - Intel EXPI9301CT:                      3.0
    1 Gbit - Intel PWLA8391GT:                      3.0
    1 Gbit - Intel 82574L:                          3.0
    1 Gbit - Intel CT Desktop Adapter (EXPI9301CT): 3.0
    1 Gbit - Intel 82579LM:                         3.0
