# file: roles/nagios/defaults/main.yaml
---

nagios_packages:
- "nagios"
- "nagios-plugins-all"
- "nagios-plugins-nrpe"
- "nsca" # Nagios Service Check Acceptor
- "python-passlib" # for Ansible htpasswd module

nagios_nrpe_packages:
- "nrpe" # Nagios Remote Plugin Executor
- "nrpe-selinux" # SELinux context for NRPE

nagios_nrpe_commands:
- token: check_load
  command: '/usr/lib64/nagios/plugins/check_load -r -w .9,.7,.5 -c 1.0,.8,.6'
